CREATE TABLE IF NOT EXISTS users (
    internal_id BIGSERIAL PRIMARY KEY,
    id VARCHAR(36) NOT NULL,
    created_on TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(320) NOT NULL,
    UNIQUE(id),
    UNIQUE(email)
);